name: Actualitzar entrenaments Strava

on:
  workflow_dispatch:

jobs:
  strava:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositori
        uses: actions/checkout@v4

      - name: Instal·lar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instal·lar dependències
        run: |
          pip install requests

      - name: Executar script
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        run: |
          python scripts/strava.py

      - name: Pujar entrenaments.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add entrenaments.json
          git commit -m "Actualització entrenaments" || echo "Sense canvis"
          git push